### ISSUE TITLE
Alfred调试报错

### ISSUE THREAD

**Issue by geekxiaoyuchen** [tiann/markdown-img-upload#20]
[2017-02-19 17:26:51][trigger.hotkey] Processing output of 'action.script' with arg ''
[2017-02-19 17:26:51][ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "upload.py", line 4, in <module>
    from qiniu import Auth, put_file
  File "qiniu/__init__.py", line 14, in <module>
    from .auth import Auth, QiniuMacAuth
  File "qiniu/auth.py", line 7, in <module>
    from requests.auth import AuthBase
ImportError: No module named requests.auth

请大神帮忙解决，我的requests库已经安装，且使用SDK做Test的时候可以成功上传，谢谢！

**Comment by tiann** [comment]
> ImportError: No module named requests.auth

你打开python命令行，import这个看看可不可以？

**Comment by tiann** [comment]
#11

**Comment by geekxiaoyuchen** [comment]
命令行是可以的呢，没有报错

**Comment by tiann** [comment]
@geekxiaoyuchen 参考 #11
